
### CREATE PRODUCT
POST http://localhost:3000/product HTTP/1.1
Content-Type:  application/json

{
  "name": "Dell XPS 13",
  "description": "Compact and powerful laptop with a 13.4-inch InfinityEdge display, Intel Core i7 processor, and 16GB RAM.",
  "price": 650000,
  "stock": 120,
  "idCategory": "66a507a6f2506fc80a27b576"
}


### GET PRODUCT
GET http://localhost:3000/api/product  HTTP/1.1

### GET PRODUCT
GET http://localhost:3000/products  HTTP/1.1

### DELETE PRODUCT
DELETE http://localhost:3000/api/product/66a1422e4215438a07d95dce  HTTP/1.1
