### Inventory API
GET http://localhost:3002/api/inventory  HTTP/1.1


### Check inventory
GET http://localhost:3002/api/inventory/66bac9b840a05ecc2d98e88e  HTTP/1.1


### add inventory
POST http://localhost:3002/api/inventory  HTTP/1.1
Content-Type: application/json

{
    "productId": "66bac9b840a05ecc2d98e88e",
    "quantity": 100
}

###
GET http://localhost:3001/api/products  HTTP/1.1


 ### GET ALL PRODUCT
GET http://localhost:3001/api/products  HTTP/1.1



### Order API

### GET ALL Order
GET http://localhost:3001/api/orders HTTP/1.1



### GET ALL users
GET  http://localhost:3001/api/users HTTP/1.1


### CREATE ORDER
POST http://localhost:3001/api/order  HTTP/1.1
Content-Type: application/json

{
    "productId": "66bac9b840a05ecc2d98e88e",
    "userId": "66bac9b840a05ecc2d98e8a3",
    "quantity": 100,
    "orderDate": "2024-07-27T14:43:35.766Z",
    "status" : "created",
    "amount": 25000
}