services:
  db:
    image: postgres
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    networks:
      - workshop

  mongodb:
    image: mongo
    ports:
      - 27017:27017
    networks:
      - workshop

  order_serv:
#    build:
#      context: ../OrderManagement
#      dockerfile: Dockerfile
    image: atemengue/order-serv:latest
    ports:
      - 3001:3001
    depends_on:
      - mongodb
    networks:
      - workshop

  inventory_serv:
#    build:
#      context: ../InventoryManagament
#      dockerfile: Dockerfile
    image: atemengue/inventory-serv:latest
    ports:
      - 3002:3002
    depends_on:
      - mongodb
    networks:
      - workshop

  payment_serv:
#    build:
#      context: ../PaymentManagement
#      dockerfile: Dockerfile
    image: atemengue/payment-serv:latest
    ports:
      - 3003:3003
    depends_on:
      - db
    networks:
      - workshop



networks:
  workshop: