services:
  db:
    image: postgres
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    networks:
      - workshop-micro-serv-docker1

  mongodb:
    image: mongo
    ports:
      - 27017:27017
    networks:
      - workshop-micro-serv-docker1

  # TODO Add the code to create the container of the service for order with the name order_serv (With me)

  # TODO Add the code to create the container of the service for inventory with the name inventory_serv

  # TODO Add the code to create the container of the service for payment with the name payment_serv



networks:
  workshop-micro-serv-docker1: