apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-deployment
  labels:
    app: payment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment
  template:
    metadata:
      name: payment-pod
      labels:
        app: payment
    spec:
      containers:
        - name: payment
          image: payment/payment-serv:latest
          ports:
            - containerPort : 3000
      restartPolicy: Always

---

apiVersion: v1
kind: Service
metadata:
  name: payment-clusterip
spec:
  type: ClusterIP
  selector:
    app: payment
  ports:
    - port: 3003
      targetPort: 3003