apiVersion: apps/v1
kind: Deployment
metadata:
  name: pricing-deployment
  labels:
    app: pricing
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pricing
  template:
    metadata:
      name: pricing-pod
      labels:
        app: pricing
    spec:
      containers:
        - name: pricing
          image: davechedjoun/pricing-serv:latest
          ports:
            - containerPort : 3004
      restartPolicy: Always

---

apiVersion: v1
kind: Service
metadata:
  name: pricing-clusterip
spec:
  type: ClusterIP
  selector:
    app: pricing
  ports:
    - port: 3004
      targetPort: 3004