apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-deployment
  labels:
    app: product
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product
  template:
    metadata:
      name: product-pod
      labels:
        app: product
    spec:
      containers:
        - name: product
          image: atemengue/product-serv:latest
          ports:
            - containerPort : 3000
      restartPolicy: Always

---

apiVersion: v1
kind: Service
metadata:
  name: product-clusterip
spec:
  type: ClusterIP
  selector:
    app: product
  ports:
    - port: 3000
      targetPort: 3000