apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-deployment
  labels:
    app: user
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user
  template:
    metadata:
      name: user-pod
      labels:
        app: user
    spec:
      containers:
        - name: user
          image: atemengue/user-serv:latest
          ports:
            - containerPort : 3004
      restartPolicy: Always

---

apiVersion: v1
kind: Service
metadata:
  name: user-clusterip
spec:
  type: ClusterIP
  selector:
    app: user
  ports:
    - port: 3004
      targetPort: 3004