version: '3.8'

services:
  app:
    build: .
    ports:
      - "8000:8000"  # Assurez-vous que c'est bien 8000
    volumes:
      - .:/var/www
    environment:
      - DB_CONNECTION=pgsql
      - DB_HOST=db
      - DB_PORT=5432
      - DB_DATABASE=pricing_management
      - DB_USERNAME=postgres
      - DB_PASSWORD=secret

  db:
    image: postgres
    environment:
      POSTGRES_DB: pricing_management
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
    ports:
      - "5432:5432"
