apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory-deployment
  labels:
    app: inventory
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inventory
  template:
    metadata:
      name: inventory-pod
      labels:
        app: inventory
    spec:
      containers:
        - name: inventory
          image: docker_config-inventory_serv:latest
          ports:
            - containerPort : 3002
      restartPolicy: Always

---

apiVersion: v1
kind: Service
metadata:
  name: inventory-clusterip
spec:
  type: ClusterIP
  selector:
    app: inventory
  ports:
    - port: 3002
      targetPort: 3002