apiVersion: v1
kind: Pod
metadata:
  name: inventory
  labels:
    app: inventory
    rel: stable
spec:
  containers:
    - name: inventory_serv
      image: docker_config-inventory_serv:latest
      ports:
        - containerPort: 3002
      resources: {}