version: '3.9'
services:
  db:
    image: postgres
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    networks:
      - workshop-micro-serv

  pgadmin:
    image: dpage/pgadmin4
    ports:
      - 80:80
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    networks:
      - workshop-micro-serv

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3003:3003
    env_file:
      - ./.env
    depends_on:
      - db
    networks:
      - workshop-micro-serv


networks:
  workshop-micro-serv: