name: Docker Build and Push

on:
  push:
    branches:
      - sync-com

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: create env file from secrets
        run: |
          echo "DATABASE_USERNAME=${{ secrets.DATABASE_USERNAME }}" >> ./PaymentManagement/.env
          echo "DATABASE_PASSWORD=${{ secrets.DATABASE_PASSWORD }}" >> ./PaymentManagement/.env
          echo "DATABASE_NAME=${{ secrets.DATABASE_NAME }}" >> ./PaymentManagement/.env
          echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" >> ./PaymentManagement/.env

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push order-serv image
        uses: docker/build-push-action@v5
        with:
          context: ./OrderManagement
          push: true
          tags: atemengue/order-serv:latest

      - name: Build and push inventory-serv image
        uses: docker/build-push-action@v5
        with:
          context: ./InventoryManagament
          push: true
          tags: atemengue/inventory-serv:latest

      - name: Build and push payment-serv image
        uses: docker/build-push-action@v5
        with:
          context: ./PaymentManagement
          push: true
          tags: atemengue/payment-serv:latest
