name: Docker Build and Push

on:
  push:
    branches:
      - docker
      - kubernetes

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: create env file from secrets
        run: |
          echo "DATABASE_USERNAME=${{ secrets.DATABASE_USERNAME }} >> .env
          echo "DATABASE_PASSWORD=${{ secrets.DATABASE_PASSWORD }} >> .env
          echo "DATABASE_NAME=${{ secrets.DATABASE_NAME }} >> .env
          echo "DATABASE_URL=${{ secrets.DATABASE_URL }} >> .env
          

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push product-serv image
        uses: docker/build-push-action@v5
        with:
          context: ../ProductManagement
          push: true
          tags: davechedjoun/product-serv:latest

      - name: Build and push order-serv image
        uses: docker/build-push-action@v5
        with:
          context: ../OrderManagement
          push: true
          tags: davechedjoun/order-serv:latest

      - name: Build and push inventory-serv image
        uses: docker/build-push-action@v5
        with:
          context: ../InventoryManagement
          push: true
          tags: davechedjoun/inventory-serv:latest

      - name: Build and push payment-serv image
        uses: docker/build-push-action@v5
        with:
          context: ../PaymentManagement
          push: true
          tags: davechedjoun/payment-serv:latest

      - name: Build and push gateway-serv image
        uses: docker/build-push-action@v5
        with:
          context: ../MicroserviceApiGateway
          push: true
          tags: davechedjoun/gateway-serv:latest
